### ISSUE TITLE
genType 이슈 관련 글 보고 

### ISSUE THREAD

**Issue by Zeta611** [iamchanii/blog2#1]
[Netlify 환경에서 GenType 패키지 설치 이슈 해결하기 ](https://imch.dev/posts/2022-06-19/fix-gentype-postinstall/)와 동일한 이슈를 겪었는데요, 이 글을 찾은 덕분에 실마리를 찾을 수 있었습니다.

다만, 저는 바로 문제가 해결되지 않았었는데요, yarn의 버그 때문이었습니다:
https://github.com/yarnpkg/berry/issues/4231#issuecomment-1179701736
`package.json`의 `resolutions`에 `gentype@^x.x.x`와 같이 추가가 되어야 하는데 `gentype@x.x.x`로 `^`가 누락되어 들어갑니다.
수동으로 이를 추가해주니 잘 됩니다.

없겠지만... 미래에 저 같은 분들을 위하여, 어디에 적을지 몰라 여기에 이슈로 남깁니다.
글 끝에 한 줄 더 추가되면 정말 좋을 것 같습니다 :)

**Comment by iamchanii** [comment]
문제가 해결되셨다니 다행입니다. 저도 해당 이슈를 해결하면서 `resolutions` 부분을 수정했는데, 이전부터 경험해왔고 암묵지로 해결한 부분이라 포스팅에는 빠뜨렸던 것 같네요. 말씀해주신 내용은 본문 하단에 추가해서 다른 분들에게도 도움이 될 수 있도록 하겠습니다. 고맙습니다!

**Comment by Zeta611** [comment]
감사합니다!
